/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.AdmPedidoController;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author diego
 */
public class AdmPedido extends javax.swing.JFrame {

    private AdmPedidoController controlador;

    public AdmPedido() {
        initComponents();

        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Administrar Pedidos");
        ajustarImagen(bannerLupita, "src/Imagenes/banner_lupita.png");
        Font font = new Font("Georgia", Font.ITALIC, 14);
        UIManager.put("OptionPane.messageFont", font);

        controlador = new AdmPedidoController(this);
        configurarTabla();
        controlador.cargarDetallesPedidos();
    }

    private void ajustarImagen(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Código Venta", "Nombre Cliente", "Fecha Venta", "Importe Final"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hace que todas las celdas no sean editables
            }
        };
        tableVentaAdmPedido.setModel(modelo);

        tableVentaAdmPedido.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int fila = tableVentaAdmPedido.getSelectedRow();
                    if (fila != -1) {
                        int codigoVenta = (int) tableVentaAdmPedido.getValueAt(fila, 0);
                        abrirVentanaDetallePedido(codigoVenta);
                    }
                }
            }
        });
    }

    public void mostrarDetallesPedidos(List<Map<String, Object>> detalles) {
        DefaultTableModel modelo = (DefaultTableModel) tableVentaAdmPedido.getModel();
        modelo.setRowCount(0);

        for (Map<String, Object> listaAdmPedidoVenta : detalles) {
            modelo.addRow(new Object[]{
                listaAdmPedidoVenta.get("CodigoVenta"),
                listaAdmPedidoVenta.get("NombreCliente"),
                listaAdmPedidoVenta.get("FechaVenta"),
                listaAdmPedidoVenta.get("ImporteFinal")
            });
        }
    }

    private void abrirVentanaDetallePedido(int codigoVenta) {
        if (controlador == null) {
        System.out.println("El controlador es null en AdmPedido");
        return;
    }
        SwingUtilities.invokeLater(() -> {
        DetallePedido detallePedido = new DetallePedido(controlador, codigoVenta);
        detallePedido.setVisible(true);
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerLupita = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVentaAdmPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerLupita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bannerLupita.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bannerLupita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bannerLupita.setMaximumSize(new java.awt.Dimension(1265, 568));
        bannerLupita.setMinimumSize(new java.awt.Dimension(1265, 568));
        bannerLupita.setPreferredSize(new java.awt.Dimension(1265, 568));
        getContentPane().add(bannerLupita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 260));

        tableVentaAdmPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoVenta", "NombreCliente", "FechaVenta", "ImporteFinal"
            }
        ));
        jScrollPane1.setViewportView(tableVentaAdmPedido);
        if (tableVentaAdmPedido.getColumnModel().getColumnCount() > 0) {
            tableVentaAdmPedido.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableVentaAdmPedido.getColumnModel().getColumn(1).setPreferredWidth(60);
            tableVentaAdmPedido.getColumnModel().getColumn(2).setPreferredWidth(30);
            tableVentaAdmPedido.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 860, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Detalles del Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 220, 30));

        jButton21.setBackground(new java.awt.Color(0, 51, 51));
        jButton21.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Volver");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 700, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        MenuAdministrador m = new MenuAdministrador();
        m.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLupita;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVentaAdmPedido;
    // End of variables declaration//GEN-END:variables
}
