package views;
import model.Consumibles;
public class AgregarConsumible extends javax.swing.JFrame {

    public AgregarConsumible() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Agregar Consumible");
        Aceptar.setEnabled(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        Validar();
    }
    public void Limpiar(){
        jTextNombre.setText(" ");
        jTextDescripcion.setText(" ");
        jTextPrecio.setText(" ");
        jTextTiempoPreparacion.setText(" ");
    }
    public void Validar(){
        
        //Validacion de Tiempo de Preparación
        jTextTiempoPreparacion.setEditable(false);
        if(jComboMododeAdquisicion.getSelectedItem().toString().equals("Preparación casera")){
            jTextTiempoPreparacion.setEditable(true);
            if(jTextTiempoPreparacion.getText().isEmpty()){
            jLabelTiempoPreparacion.setText("*");
            }else{
            jLabelTiempoPreparacion.setText("");
            }
        }else{
            jTextTiempoPreparacion.setEditable(false);
            jTextTiempoPreparacion.setText("");
            jLabelTiempoPreparacion.setText("");
        }
        
        // Validacion de Tipo
        if (jComboTipoConsumible.getSelectedItem().toString().equals("Seleccione")) {
            jLabelTipoConsumible.setText("*");
        } else {
            jLabelTipoConsumible.setText("");
        }
        
        // Validacion de Modo de Adquisicion
        if (jComboMododeAdquisicion.getSelectedItem().toString().equals("Seleccione")) {
            jLabelModoAdquisicion.setText("*");
        } else {
            jLabelModoAdquisicion.setText("");
        }
        
        //Validacion de nombre
        if(jTextNombre.getText().isEmpty()){
            jLabelNombre.setText("*");
        }else{
            jLabelNombre.setText("");
        }
        
        //Validacion de Descripcion
        if(jTextDescripcion.getText().isEmpty()){
            jLabelDescripcion.setText("*");
        }else{
            jLabelDescripcion.setText("");
        }

        //Validacion de Precio
        if(jTextPrecio.getText().isEmpty()){
            jLabelPrecio.setText("*");
        }else{
            jLabelPrecio.setText("");
        }
       //Validacion general
        if(jTextNombre.getText().isEmpty()||jTextDescripcion.getText().isEmpty()||jTextPrecio.getText().isEmpty()||jComboTipoConsumible.getSelectedItem().toString().equals("Seleccione")||jComboMododeAdquisicion.getSelectedItem().toString().equals("Seleccione")){
            Aceptar.setEnabled(false);
        }else{
            Aceptar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboMododeAdquisicion = new javax.swing.JComboBox<>();
        jLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextTiempoPreparacion = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        jLabelTiempoPreparacion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipoConsumible = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLabelModoAdquisicion = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jComboTipoConsumible = new javax.swing.JComboBox<>();
        jLabelPrecio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboMododeAdquisicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Comprado", "Preparación casera" }));
        jComboMododeAdquisicion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboMododeAdquisicionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboMododeAdquisicionKeyTyped(evt);
            }
        });
        jPanel1.add(jComboMododeAdquisicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 153, 157, -1));

        jLabel.setText("Descripción:");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 113, -1, -1));

        jLabel20.setText("Tiempo de preparación:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 203, -1, -1));

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 61, 211, -1));

        jTextTiempoPreparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextTiempoPreparacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTiempoPreparacionKeyTyped(evt);
            }
        });
        jPanel1.add(jTextTiempoPreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 197, 92, -1));

        Aceptar.setBackground(new java.awt.Color(0, 51, 51));
        Aceptar.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 243, -1, -1));

        jLabelTiempoPreparacion.setForeground(new java.awt.Color(153, 0, 0));
        jLabelTiempoPreparacion.setText("*");
        jPanel1.add(jLabelTiempoPreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 203, -1, -1));

        jLabelNombre.setForeground(new java.awt.Color(153, 0, 0));
        jLabelNombre.setText("*");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 67, -1, -1));

        jLabelTipoConsumible.setForeground(new java.awt.Color(153, 0, 0));
        jLabelTipoConsumible.setText("*");
        jPanel1.add(jLabelTipoConsumible, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 158, -1, -1));

        jTextDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(jTextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 107, 490, -1));

        jLabelModoAdquisicion.setForeground(new java.awt.Color(153, 0, 0));
        jLabelModoAdquisicion.setText("*");
        jPanel1.add(jLabelModoAdquisicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 158, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel13.setText("Nuevo Consumible");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, -1, -1));

        jTextPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioActionPerformed(evt);
            }
        });
        jTextPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioKeyTyped(evt);
            }
        });
        jPanel1.add(jTextPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 61, 167, -1));

        jLabelDescripcion.setForeground(new java.awt.Color(153, 0, 0));
        jLabelDescripcion.setText("*");
        jPanel1.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 113, -1, -1));

        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 67, -1, -1));

        jLabel15.setText("Tipo:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 158, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 243, -1, -1));

        jComboTipoConsumible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dulce", "Salado" }));
        jComboTipoConsumible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoConsumibleActionPerformed(evt);
            }
        });
        jComboTipoConsumible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboTipoConsumibleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboTipoConsumibleKeyTyped(evt);
            }
        });
        jPanel1.add(jComboTipoConsumible, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 153, 137, -1));

        jLabelPrecio.setForeground(new java.awt.Color(153, 0, 0));
        jLabelPrecio.setText("*");
        jPanel1.add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 61, -1, -1));

        jLabel10.setText("Modo de adquisicion:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 158, -1, -1));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 67, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consumibles.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioKeyReleased
        Validar();
    }//GEN-LAST:event_jTextPrecioKeyReleased

    private void jTextPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextPrecioKeyTyped

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyReleased
        Validar();
    }//GEN-LAST:event_jTextNombreKeyReleased

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed

        Consumibles cons = new Consumibles();
        //Asignacion de las variables
        cons.nombre=jTextNombre.getText();
        cons.descripcion=jTextDescripcion.getText();
        cons.tipo=jComboTipoConsumible.getSelectedItem();
        cons.precio=jTextPrecio.getText();
        cons.modoDeAdquisicion= jComboMododeAdquisicion.getSelectedItem();
        cons.tiempoDePreparacion=jTextTiempoPreparacion.getText();

        //Agregar consumible
        cons.AgregarConsumibles();
        Limpiar();
        this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void jTextDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDescripcionKeyReleased
        Validar();
    }//GEN-LAST:event_jTextDescripcionKeyReleased

    private void jTextDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDescripcionKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextDescripcionKeyTyped

    private void jComboTipoConsumibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoConsumibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoConsumibleActionPerformed

    private void jComboTipoConsumibleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboTipoConsumibleKeyReleased
       Validar();
    }//GEN-LAST:event_jComboTipoConsumibleKeyReleased

    private void jComboTipoConsumibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboTipoConsumibleKeyTyped
        
    }//GEN-LAST:event_jComboTipoConsumibleKeyTyped

    private void jComboMododeAdquisicionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboMododeAdquisicionKeyReleased
        Validar();
    }//GEN-LAST:event_jComboMododeAdquisicionKeyReleased

    private void jComboMododeAdquisicionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboMododeAdquisicionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMododeAdquisicionKeyTyped

    private void jTextTiempoPreparacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTiempoPreparacionKeyReleased
        Validar();
    }//GEN-LAST:event_jTextTiempoPreparacionKeyReleased

    private void jTextTiempoPreparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTiempoPreparacionKeyTyped
    }//GEN-LAST:event_jTextTiempoPreparacionKeyTyped

    private void jTextPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarConsumible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboMododeAdquisicion;
    private javax.swing.JComboBox<String> jComboTipoConsumible;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelModoAdquisicion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTiempoPreparacion;
    private javax.swing.JLabel jLabelTipoConsumible;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextTiempoPreparacion;
    // End of variables declaration//GEN-END:variables
}
