package views;
import model.Cargos;
public class AgregarCargo extends javax.swing.JFrame {
    public AgregarCargo() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Agregar Cargo");
        Aceptar.setEnabled(false);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    public void Limpiar(){
        jTextNombre.setText(" ");
        jTextSueldo.setText(" ");
        jTextDescripcion.setText(" ");
    }
    public void Validar(){
        
        //Validacion de nombre
        if(jTextNombre.getText().isEmpty()){
            jLabelNom.setText("*");
        }else{
            jLabelNom.setText("");
        }
        
        //Validacion de Descripcion
        if(jTextDescripcion.getText().isEmpty()){
            jLabelDescripcion.setText("*");
        }else{
            jLabelDescripcion.setText("");
        }
        
       
        //Validacion de Sueldo
        if(jTextSueldo.getText().isEmpty()){
            jLabelSueldo.setText("*");
        }else{
            jLabelSueldo.setText("");
        }
        
       //Validacion general
        if(jTextNombre.getText().isEmpty()||jTextDescripcion.getText().isEmpty()||jTextSueldo.getText().isEmpty()){
            Aceptar.setEnabled(false);
        }else{
            Aceptar.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        jLabelNom = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelSueldo = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));

        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 211, -1));

        Aceptar.setBackground(new java.awt.Color(0, 51, 51));
        Aceptar.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabelNom.setForeground(new java.awt.Color(153, 0, 0));
        jLabelNom.setText("*");
        jPanel1.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jTextDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(jTextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 460, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel13.setText("Nuevo Cargo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        jLabelDescripcion.setForeground(new java.awt.Color(153, 0, 0));
        jLabelDescripcion.setText("*");
        jPanel1.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jTextSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextSueldoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 70, 140, -1));

        jLabel3.setText("Sueldo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabelSueldo.setForeground(new java.awt.Color(153, 0, 0));
        jLabelSueldo.setText("*");
        jPanel1.add(jLabelSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabel.setText("Descripción:");
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cargo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyReleased
        Validar();
    }//GEN-LAST:event_jTextNombreKeyReleased

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        Cargos car = new Cargos();
        //Asignacion de las variables
        car.nombre=jTextNombre.getText();
        car.descripcion=jTextDescripcion.getText();
        car.sueldo=jTextSueldo.getText();

        //Agregar cargo
        car.AgregarCargo();
        Limpiar(); 
        this.dispose();

    }//GEN-LAST:event_AceptarActionPerformed

    private void jTextDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDescripcionKeyReleased
        Validar();
    }//GEN-LAST:event_jTextDescripcionKeyReleased

    private void jTextDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDescripcionKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isDigit(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextDescripcionKeyTyped

    private void jTextSueldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSueldoKeyReleased
        Validar();
    }//GEN-LAST:event_jTextSueldoKeyReleased

    private void jTextSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSueldoKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextSueldoKeyTyped

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
