/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.text.DecimalFormat;
import controllers.AdmPedidoController;
import java.awt.BorderLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class DetallePedido extends javax.swing.JFrame {

    private AdmPedidoController controlador;

    public DetallePedido(AdmPedidoController controlador, int codigoVenta) {
        this.controlador = controlador;
        if (this.controlador == null) {
            throw new IllegalArgumentException("El controlador no puede ser null");
        }
        setTitle("Detalles del Pedido - Código Venta: " + codigoVenta);
        setSize(800, 600);
        setLocationRelativeTo(null);

        tableDetalles = new JTable();
        JScrollPane scrollPane = new JScrollPane(tableDetalles);
        labelTotalPedido = new JLabel();
        labelTotalPedido.setHorizontalAlignment(JLabel.RIGHT);
        labelTotalPedido.setFont(new Font("Segoe UI Black", Font.ITALIC, 14));

        JPanel panelPrincipal = new JPanel(new BorderLayout());
        panelPrincipal.add(scrollPane, BorderLayout.CENTER);
        panelPrincipal.add(labelTotalPedido, BorderLayout.SOUTH);

        setLayout(new BorderLayout());
        add(panelPrincipal, BorderLayout.CENTER);

        System.out.println("tablaDetallePedido inicializada");

        cargarDetallesPedido(codigoVenta);
    }

    private void cargarDetallesPedido(int codigoVenta) {
        System.out.println("Cargando detalles para el pedido: " + codigoVenta);
        List<Map<String, Object>> detalles = controlador.obtenerDetallesPedido(codigoVenta);
        System.out.println("Detalles obtenidos: " + (detalles != null ? detalles.size() : "null"));

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Código Detalle", "Nombre Producto", "Cantidad", "Precio", "Total"}
        );

        DecimalFormat df = new DecimalFormat("#.0");
        double totalPedido = 0.0;

        for (Map<String, Object> detalle : detalles) {
            System.out.println("Procesando detalle: " + detalle);
            Object codigoDetalle = detalle.get("CodigoDetalleVenta");
            Object nombreProducto = detalle.get("NombreProducto");
            Object cantidad = detalle.get("Cantidad");
            Object precio = detalle.get("Precio");
            Object total = detalle.get("Total");

            System.out.println("Valores obtenidos: " + codigoDetalle + ", " + nombreProducto + ", " + cantidad + ", " + precio + ", " + total);

            double precioDouble = precio != null ? ((Number) precio).doubleValue() : 0.0;
            double cantidadDouble = cantidad != null ? ((Number) cantidad).doubleValue() : 0.0;
            double totalDouble = precioDouble * cantidadDouble;
            totalPedido += totalDouble;

            modelo.addRow(new Object[]{
                codigoDetalle != null ? codigoDetalle : "N/A",
                nombreProducto != null ? nombreProducto : "N/A",
                cantidad != null ? cantidad : "N/A",
                precio != null ? df.format(precioDouble) : "N/A",
                df.format(totalDouble)
            });
        }
        if (tableDetalles == null) {
            System.out.println("tablaDetallePedido es null");
            return;
        }

        tableDetalles.setModel(modelo);
        labelTotalPedido.setText("Total del pedido: S/ " + totalPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalles = new javax.swing.JTable();
        labelTotalPedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodigoDetalleVenta", "NombreProducto", "Cantidad", "Precio", "Total"
            }
        ));
        tableDetalles.setMaximumSize(new java.awt.Dimension(160, 0));
        jScrollPane2.setViewportView(tableDetalles);
        if (tableDetalles.getColumnModel().getColumnCount() > 0) {
            tableDetalles.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableDetalles.getColumnModel().getColumn(1).setPreferredWidth(40);
            tableDetalles.getColumnModel().getColumn(2).setPreferredWidth(30);
            tableDetalles.getColumnModel().getColumn(3).setPreferredWidth(30);
            tableDetalles.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 530, 250));

        labelTotalPedido.setText("Total Pedido:");
        getContentPane().add(labelTotalPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallePedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotalPedido;
    private javax.swing.JTable tableDetalles;
    // End of variables declaration//GEN-END:variables
}
